/**
 Author: Sofien
**/

DROP SCHEMA IF EXISTS solo;

CREATE SCHEMA solo;
USE solo;


create table roles (
        id integer generated by default as identity,
        date_created timestamp,
        last_updated timestamp,
        version integer,
        role_name varchar(50) not null,
        primary key (id)
    );
	
    create table user_role (
        user_id integer not null,
        role_id integer not null
    );
	
    create table users (
        id integer generated by default as identity,
        date_created timestamp,
        last_updated timestamp,
        version integer,
        email varchar(255),
        enabled boolean,
        encrypted_password varchar(255),
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        username varchar(255) not null,
        primary key (id)
    );
	
alter table user_role add constraint FKt7e7djp752sqn6w22i6ocqy6q foreign key (role_id) references roles ;
alter table user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users ;
      